### ISSUE TITLE
Thanks for your help!

### ISSUE THREAD

**Issue by merencia** [boralyl/github-custom-component-tutorial#11]
I'd like to express my gratitude for sharing your guide on building a custom component. As I'm not a Python developer, I encountered some difficulties understanding certain aspects in the documentation. However, after following your tutorial, I was able to successfully implement an integration for my alarm central.

Here is the repository:  https://github.com/merencia/amt8000-hass-integration

Thank you!

**Comment by boralyl** [comment]
I'm glad this was helpful to you :tada: !  At some point this tutorial needs some updates as a lot has changed since I first wrote it.
