### ISSUE TITLE
unsub_options_update_listener reference?

### ISSUE THREAD

**Issue by thlucas1** [boralyl/github-custom-component-tutorial#12]
Hi Aaron - your tutorial on building a custom component config (and options) flow really helped me out.  Thank you so much for putting this together.

One question regarding the options flow coding in `__init__.py` - you mention a `unsub_options_update_listener` reference:  "__The add_updated_listener method returns an unsubscribe function that we will store for later so that we can clean up the listener if the config entry is removed by the user.__"

and the corresponding code:
```
hass_data["unsub_options_update_listener"] = unsub_options_update_listener
```

I don't see that referenced anywhere else.  Should something be done in `async_unload_entry` to remove the update listener?  or does that happen automatically by HASS maybe?

**Comment by boralyl** [comment]
I haven't done a good job of updating the blog posts as code in the repository is changed.  That particular bit of code is no longer needed and is done in a different way that you can see here: https://github.com/boralyl/github-custom-component-tutorial/commit/9bd26fc0c3f31c181b35f0dcce5cf40dea9d60c5

If I ever get time I'd love to do an updated post as a lot of things have changed in 3 years, but I'm not sure when I might be able to get around to that.

**Comment by thlucas1** [comment]
No problem at all - we are all busy, and completely understand.  You pointed me in the right direction, and that was what I needed.  Again, love the tutorials; straightforward explanation, real world examples, awesomeness!
Thanks again - will close this issue with this comment.
