### ISSUE TITLE
pythonpackage.yaml no longer works

### ISSUE THREAD

**Issue by TomHart** [boralyl/github-custom-component-tutorial#3]
I get this error

```
Error: Unable to process command '::set-env name=PY::cdff5fd5920138f547cdcfe8e449053ac96b7b85b421aa6a9c8e2b6b4a274b31' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Do you know what I need to update to get it working?

**Comment by boralyl** [comment]
That command has been deprecated and was removed: https://github.com/boralyl/github-custom-component-tutorial/commit/f704192c71a09e015f03f1c6d69030dac3dbda0c#diff-dc70c06d1332c2de7fa275bdba5eb6a144c5e08ea447b965f9f621c93a56c7bb

I'd recommend using the latest version, make sure you are on the main branch when looking at the code in the repository: https://github.com/boralyl/github-custom-component-tutorial/blob/main/.github/workflows/pythonpackage.yaml

**Comment by TomHart** [comment]
Thanks!
