### ISSUE TITLE
source not working: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by msavazzi** [boralyl/github-custom-component-tutorial#8]
I've downloaded the full folder. Copied the "github_custom" folder and I get an error 500: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Am I doing something wrong?
Thanks,
M

**Comment by boralyl** [comment]
Thanks for opening an issue!  There was a dependency conflict with home assistant.  I've pushed up a commit that will resolve that issue: https://github.com/boralyl/github-custom-component-tutorial/commit/c7ad901059a517cfd57f440c22b8cf748285fb68
